version: '3'
services:
  frontend:
    build: ./frontend
    container_name: 'sake-frontend'
    working_dir: '/frontend'
    tty: true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    
  backend:
    restart: always
    build: ./backend
    container_name: 'sake-backend'
    working_dir: '/sake'
    tty: true
    volumes:
      - .:/sake
    ports:
      - '8000:8000'


